name: Update News

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Environment
        run: |
          echo "==== ENVIRONMENT CHECK ===="
          if [ -n "$GOOGLE_API_KEY" ]; then echo "✓ GOOGLE_API_KEY is set"; else echo "✗ GOOGLE_API_KEY is missing"; fi
          if [ -n "$NEWS_API_KEY" ]; then echo "✓ NEWS_API_KEY is set"; else echo "✗ NEWS_API_KEY is missing"; fi
          if [ -n "$NYT_API_KEY" ]; then echo "✓ NYT_API_KEY is set"; else echo "✗ NYT_API_KEY is missing"; fi
          echo "Current directory:"
          pwd
          ls -la

      - name: Run script with debug
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
        run: |
          echo "==== RUNNING SCRIPT ===="
          python -u news_scraper.py

      - name: Verify JSON Output
        run: |
          echo "==== VERIFYING JSON ===="
          if [ -f conflict_news.json ]; then
            echo "JSON file exists"
            echo "File size: $(wc -c < conflict_news.json) bytes"
            echo "File contents:"
            cat conflict_news.json
            if [ ! -s conflict_news.json ]; then
              echo "ERROR: JSON file is empty"
              exit 1
            fi
          else
            echo "ERROR: JSON file not found"
            exit 1
          fi

      - name: Commit and push if changed
        run: |
          echo "==== COMMITTING CHANGES ===="
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add conflict_news.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update conflict news [skip ci]"
            git push origin main
          fi
