name: Update News

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
        run: |
          python -u news_scraper.py
          echo "Content of conflict_news.json after script:"
          cat conflict_news.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add conflict_news.json
          git commit -m "Update conflict news [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
