name: Update News

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script and verify output
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
        run: |
          # Backup existing file
          if [ -f conflict_news.json ]; then
            cp conflict_news.json conflict_news.backup.json
          fi
          
          # Run the script
          python -u news_scraper.py
          
          # Verify the new file
          if [ ! -f conflict_news.json ]; then
            echo "Error: conflict_news.json was not created"
            if [ -f conflict_news.backup.json ]; then
              cp conflict_news.backup.json conflict_news.json
            fi
            exit 1
          fi
          
          # Check if file is valid JSON and has content
          if ! jq empty conflict_news.json 2>/dev/null || [ ! -s conflict_news.json ]; then
            echo "Error: conflict_news.json is empty or invalid"
            if [ -f conflict_news.backup.json ]; then
              cp conflict_news.backup.json conflict_news.json
            fi
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add conflict_news.json
          git commit -m "Update conflict news [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
