name: Update News

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
        run: python news_scraper.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet conflict_news.json || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add conflict_news.json
          git commit -m "Update conflict news [skip ci]"
          git push
